# Generated by Django 6.0.2 on 2026-03-12 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.FloatField()),
                ('percentile', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_tracker.exam')),
            ],
            options={
                'verbose_name_plural': 'marks',
            },
        ),
        migrations.CreateModel(
            name='SubjectMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.FloatField()),
                ('maths', models.FloatField()),
                ('reasoning', models.FloatField()),
                ('general_studies', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_tracker.marks')),
            ],
            options={
                'verbose_name_plural': 'Subject wise marks',
            },
        ),
    ]
